### ISSUE TITLE
Label not visible on main menu

### ISSUE THREAD

**Issue by Rombond** [Banalian/BitBiscuit-GMTK2023#1]
Label at the bottom left with "GMTK Game Jam 2023" is not visible
here a proof:
![menu](https://github.com/Banalian/BitBiscuit-GMTK2023/assets/13875526/fd71fa47-6fd0-4d48-bb26-9e062bb2f5dc)

**Comment by Banalian** [comment]
still learning UI stuff on unity x), won't fix since it was just a gamejam project.
