### ISSUE TITLE
UI diseappear when focus is lost

### ISSUE THREAD

**Issue by Rombond** [Banalian/BitBiscuit-GMTK2023#2]
When I alt+tab or click on another window on a different screen, the game freezes, and the UI disappears
Here a proof:
![lost_focus](https://github.com/Banalian/BitBiscuit-GMTK2023/assets/13875526/88ef86a1-2067-434c-bdc4-031b3ca9cf27)

**Comment by Banalian** [comment]
That's some unity shenanigans, no idea how to fix that, but won't fix anyway as this was just for the gamejam
